package Runner;

import Logic.AppsManagement;
import Logic.GitHubService;
import Logic.NxApp;
import java.awt.FontMetrics;
import java.io.IOException;
import java.io.InputStream;
import java.net.HttpURLConnection;
import java.net.URL;
import java.nio.file.Files;
import java.nio.file.Path;
import java.nio.file.Paths;
import java.nio.file.StandardCopyOption;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.JTableHeader;
import javax.swing.table.TableColumnModel;
import javax.swing.table.TableColumn;

public class MainMenu extends javax.swing.JFrame {

    ArrayList<NxApp> apps = AppsManagement.addApps();
    private GitHubService gitHubService;

    public MainMenu() {
        initComponents();
        //  welcomeMessage();
        setLocationRelativeTo(null);
        setTitle("Nintendo Switch Homebrew Java Updater v1.0.0");
        configureTable();
        addElements();
        try {
            gitHubService = new GitHubService();
        } catch (IOException e) {
            JOptionPane.showMessageDialog(this, "Error while connecting to Github: " + e.getMessage(),
                    "Warning", JOptionPane.WARNING_MESSAGE);
        }
    }

    private void downloadFile(String fileURL, String outputPath) throws IOException {
        URL url = new URL(fileURL);
        HttpURLConnection httpConn = (HttpURLConnection) url.openConnection();
        httpConn.setRequestMethod("GET");
        httpConn.setConnectTimeout(30000);
        httpConn.setReadTimeout(60000);
        httpConn.setInstanceFollowRedirects(true);

        Path outputFile = Paths.get(outputPath);
        Path parentDir = outputFile.getParent();
        if (parentDir != null && !Files.exists(parentDir)) {
            Files.createDirectories(parentDir);
            System.out.println("Folder Created: " + parentDir);
        }

        try (InputStream inputStream = httpConn.getInputStream()) {
            Files.copy(inputStream, outputFile, StandardCopyOption.REPLACE_EXISTING);
            System.out.println("File Created: " + outputFile.toAbsolutePath());
        } finally {
            httpConn.disconnect();
        }
    }

    private void welcomeMessage() {
        JOptionPane.showMessageDialog(null, "This Application was developed by EternalRed05, any sugerences can be made via github issues. Thanks for using!.", "Welcome", JOptionPane.INFORMATION_MESSAGE);
    }

    private void addElements() {
        DefaultTableModel model = (DefaultTableModel) appTable.getModel();
        model.setRowCount(0);
        for (NxApp n : apps) {
            Object[] o = new Object[]{n.getName(), n.getRepoOwner(), n.getUrl(), n.getVersion()};
            model.addRow(o);
        }
        autoResizeColumns();

    }

    private void configureTable() {
        String[] columnas = {"App Name", "Developer", "Source", "Latest Version"};
        DefaultTableModel model = new DefaultTableModel(columnas, 0) {
            @Override
            public boolean isCellEditable(int row, int column) {
                return false;
            }
        };
        appTable.setModel(model);
        appTable.getTableHeader().setReorderingAllowed(false);

    }

    private void autoResizeColumns() {
        JTableHeader header = appTable.getTableHeader();
        TableColumnModel columnModel = appTable.getColumnModel();
        FontMetrics headerFontMetrics = header.getFontMetrics(header.getFont());
        FontMetrics cellFontMetrics = appTable.getFontMetrics(appTable.getFont());

        for (int col = 0; col < appTable.getColumnCount(); col++) {
            TableColumn column = columnModel.getColumn(col);
            String headerValue = (String) column.getHeaderValue();
            int headerWidth = headerFontMetrics.stringWidth(headerValue) + 12;

            int maxCellWidth = headerWidth;
            for (int row = 0; row < appTable.getRowCount(); row++) {
                Object value = appTable.getValueAt(row, col);
                if (value != null) {
                    String text = value.toString();
                    int cellWidth = cellFontMetrics.stringWidth(text) + 12;
                    if (cellWidth > maxCellWidth) {
                        maxCellWidth = cellWidth;
                    }
                }
            }

            column.setPreferredWidth(maxCellWidth);
            column.setMinWidth(maxCellWidth);

        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        appTable = new javax.swing.JTable();
        downloadAll = new javax.swing.JButton();
        progressBar = new javax.swing.JProgressBar();
        lblStatus = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jButton1.setText("Download Selected");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        appTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(appTable);

        downloadAll.setText("Download All Apps");
        downloadAll.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                downloadAllActionPerformed(evt);
            }
        });

        lblStatus.setText("Actual Status");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(137, 137, 137)
                .addComponent(downloadAll, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(204, 204, 204)
                .addComponent(lblStatus)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(53, 53, 53))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(299, Short.MAX_VALUE)
                .addComponent(progressBar, javax.swing.GroupLayout.PREFERRED_SIZE, 525, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(210, 210, 210))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(41, 41, 41)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 952, Short.MAX_VALUE)
                    .addGap(41, 41, 41)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(523, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(downloadAll, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(lblStatus, javax.swing.GroupLayout.Alignment.TRAILING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(progressBar, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(23, 23, 23))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(102, 102, 102)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 414, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(102, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void downloadAllActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_downloadAllActionPerformed

        downloadAll.setEnabled(false);
        jButton1.setEnabled(false);
        downloadAll.setText("Downloading...");

        // progress bar config
        progressBar.setValue(0);
        progressBar.setMaximum(apps.size());
        progressBar.setStringPainted(true);
        lblStatus.setText("Starting Downloads...");

        new Thread(() -> {
            int successCount = 0;
            StringBuilder errors = new StringBuilder();

            for (int i = 0; i < apps.size(); i++) {
                NxApp app = apps.get(i);
                final int currentIndex = i + 1;

                javax.swing.SwingUtilities.invokeLater(() -> {
                    lblStatus.setText("Downloading " + app.getName() + " (" + currentIndex + "/" + apps.size() + ")");
                });

                String version = app.getVersion();
                if (version == null || version.equals("Unknown") || version.equals("Error/No release")) {
                    errors.append("• ").append(app.getName()).append(": The Version is not available\n");

                    updateProgress(i + 1);
                    continue;
                }

                try {
                    String downloadUrl = gitHubService.getAssetDownloadUrl(app.getRepoOwner(), app.getRepoName());

                    if (downloadUrl != null) {
                        String fileName = app.getName().replaceAll("\\s+", "_") + "_" + version + ".zip";
                        String outputPath = System.getProperty("user.home") + "/Downloads/NxAppDownloader/" + fileName;

                        downloadFile(downloadUrl, outputPath);
                        successCount++;
                        System.out.println("Succesfull Download " + app.getName() + " stored in " + outputPath);
                    } else {
                        errors.append("• ").append(app.getName()).append(": The File couldn't be downloaded correctly, check your internet connection.\n");
                    }
                } catch (Exception e) {
                    errors.append("• ").append(app.getName()).append(": ").append(e.getMessage()).append("\n");
                    System.err.println("Error: " + e.getMessage());
                    System.err.println("Error while downloading " + app.getName() + ": " + e.getMessage());
                    e.printStackTrace();
                }

                updateProgress(i + 1);
            }

            final int finalSuccess = successCount;
            final String finalErrors = errors.toString();
            javax.swing.SwingUtilities.invokeLater(() -> {
                String message = "Downloads were completed.\nSuccess: " + finalSuccess + "\nFailed: " + (apps.size() - finalSuccess);
                if (finalErrors.length() > 0) {
                    message += "\n\nErrors:\n" + finalErrors;
                }
                JOptionPane.showMessageDialog(MainMenu.this, message, "Results",
                        (finalSuccess == apps.size()) ? JOptionPane.INFORMATION_MESSAGE : JOptionPane.WARNING_MESSAGE);

                downloadAll.setEnabled(true);
                jButton1.setEnabled(true);
                downloadAll.setText("Download All Apps");
                lblStatus.setText("Succesfull");
                progressBar.setValue(0);
            });
        }).start();
    }//GEN-LAST:event_downloadAllActionPerformed
    private void updateProgressSelected(int current, int total) {
        javax.swing.SwingUtilities.invokeLater(() -> {
            progressBar.setValue(current);
            progressBar.setString(current + "/" + total);
        });
    }

    private void updateProgress(int value) {
        javax.swing.SwingUtilities.invokeLater(() -> {
            progressBar.setValue(value);
            progressBar.setString(value + "/" + apps.size());
        });
    }
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        int[] selectedRows = appTable.getSelectedRows();

        if (selectedRows.length == 0) {
            JOptionPane.showMessageDialog(this,
                    "Please select at least one application from the table.",
                    "No selection",
                    JOptionPane.WARNING_MESSAGE);

        } else {
            ArrayList<NxApp> selectedApps = new ArrayList<>();
            for (int row : selectedRows) {
                selectedApps.add(apps.get(row));
            }

            downloadAll.setEnabled(false);
            jButton1.setEnabled(false);
            jButton1.setText("Downloading selected...");

            progressBar.setValue(0);
            progressBar.setMaximum(selectedRows.length);
            progressBar.setStringPainted(true);
            lblStatus.setText("Starting downloads for selected apps...");

            new Thread(() -> {
                int successCount = 0;
                StringBuilder errors = new StringBuilder();

                for (int i = 0; i < selectedApps.size(); i++) {
                    NxApp app = selectedApps.get(i);
                    final int currentIndex = i + 1;

                    javax.swing.SwingUtilities.invokeLater(() -> {
                        lblStatus.setText("Downloading " + app.getName() + " (" + currentIndex + "/" + selectedApps.size() + ")");
                    });

                    String version = app.getVersion();
                    if (version == null || version.equals("Unknown") || version.equals("Error/No release")) {
                        errors.append("• ").append(app.getName()).append(": Version not available\n");
                        updateProgressSelected(currentIndex, selectedApps.size());
                        continue;
                    }

                    try {
                        String downloadUrl = gitHubService.getAssetDownloadUrl(app.getRepoOwner(), app.getRepoName());
                        if (downloadUrl != null) {

                            String fileName = app.getName().replaceAll("\\s+", "_") + "_" + version + ".zip";
                            String outputPath = System.getProperty("user.home") + "/Downloads/NxAppDownloader/" + fileName;

                            downloadFile(downloadUrl, outputPath);
                            successCount++;
                            System.out.println("Successfully downloaded " + app.getName() + " to " + outputPath);
                        } else {
                            errors.append("• ").append(app.getName()).append(": No asset (ZIP) found in the release\n");
                        }
                    } catch (Exception e) {
                        errors.append("• ").append(app.getName()).append(": ").append(e.getMessage()).append("\n");
                        System.err.println("Error downloading " + app.getName() + ": " + e.getMessage());
                        e.printStackTrace();
                    }

                    updateProgressSelected(currentIndex, selectedApps.size());
                }

                final int finalSuccess = successCount;
                final String finalErrors = errors.toString();
                final int totalSelected = selectedApps.size();

                javax.swing.SwingUtilities.invokeLater(() -> {
                    String message = "Download completed for selected apps.\nSuccess: " + finalSuccess + "\nFailed: " + (totalSelected - finalSuccess);
                    if (finalErrors.length() > 0) {
                        message += "\n\nErrors:\n" + finalErrors;
                    }
                    JOptionPane.showMessageDialog(MainMenu.this, message, "Result (Selected)",
                            (finalSuccess == totalSelected) ? JOptionPane.INFORMATION_MESSAGE : JOptionPane.WARNING_MESSAGE);

                    downloadAll.setEnabled(true);
                    jButton1.setEnabled(true);
                    jButton1.setText("Download Selected");
                    lblStatus.setText("Ready");
                    progressBar.setValue(0);
                });
            }).start();
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainMenu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable appTable;
    private javax.swing.JButton downloadAll;
    private javax.swing.JButton jButton1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblStatus;
    private javax.swing.JProgressBar progressBar;
    // End of variables declaration//GEN-END:variables
}
